### PR TITLE
Correct previous partners change

### PR DESCRIPTION
**Pull request by rarafon**
I changed the api.getProjPartnersLeaders with the assumption that the code in partner.js in the route folder was the correct in pr #165 .

It turns out that the page '/partners' probably isn't ever used. It also originally had conflicting code, and I made the wrong judgement on which code to follow. Instead, it conflicts with the other files that actually used partners data, and I should have looked at those instead.

I reverted back to what it was previously, but now it will also check if the results are empty. 

Please see https://github.com/dandahle/Catalyst-AppVetting/pull/165/commits/3b4fc367ca2008eb82fc173ff055ec61c338d68c for the previous change.

The error I was encountering previous was when there were no partners found in the search, which crashed the server since the code always expected results.

### CODE REVIEW

**Comment by rarafon** [comment]
I think I understand now after writing a reply somewhere else.

The GET '/partners' and POST '/partners/getPartnerAssoc' aren't used anymore and it was written by a previous developer. Then, someone else modified api.getProjPartnersLeaders and now it always has to be used after api.getDocumentSite (or a function that creates res.local.results) or else it crashes the server. 

The second developer didn't correct the functions that used it previously because it's not used anywhere else which is why the error that I encountered was never found before.

Those two requests aren't used anywhere else in the repository from what I can tell searching with Visual Studio Code. Now, api.getProjPartnersLeaders does not need another function to be called first, and it can work on its own without crashing.

**Comment by dandahle** [comment]
Hi Andy - thank you checking this out. I will do a merge and pull the code this morning to check things out. I suppose we should keep a log somewhere of the unused code people run across so we can be a little systematic about excising it. If there is another OSU team to move testing forward removing dead or orphaned code will be part of the scope. Will let you know what I find later this morning. ==> Dan

**Comment by dandahle** [comment]
These updates correct the problem. The client records in Site Assessment and Project Summary now load properly.

**Comment by ironmikesh** [comment]
Thank you so much, Andy!

Mike

**Pull request merged**
